arextest/arex

- src/common/locale/en.json
- src/common/locale/zh.json
- src/modules/analysis/diff/analysis-diff.ts
- src/modules/analysis/index.ts
- src/modules/analysis/menu/analysis-menu.ts
- src/view/analysis/Analysis.vue
- src/view/analysis/detail/AnalysisDetail.vue
- src/view/analysis/diff/AnalysisDiff.vue
- src/view/analysis/diff/NewMsgWithDiffJsonEditor.vue
- src/view/analysis/header/AnalysisHeader.vue
- src/view/analysis/menu/MenuSetting.vue
> add some uncommitted code

- src/components/login/index.less
- src/components/login/index.tsx
- src/layouts/mainbox.tsx
- src/services/LoginService.ts
> Dev lpf login

- src/components/TooltipButton/index.tsx
- src/components/appSetting/NodesIgnore/PathCollapse.tsx
- src/components/appSetting/Replay/FormItem/ExcludeOperation.tsx
- src/components/http/extra/tabs/request/Mock.tsx
- src/components/menus/AppMenu.tsx
- src/components/menus/CollectionMenu/index.tsx
- src/components/panes/EnvironmentPage.tsx
- src/components/panes/ReplayCasePage.tsx
- src/components/panes/ReplayDiffScenesPage/DIffDrawer.tsx
- src/components/panes/ReplayDiffScenesPage/DiffScenes.tsx
- src/components/panes/ReplayDiffScenesPage/index.tsx
- src/components/replay/ReplayReport.tsx
1. casePage diffNode ignore
2. component TooltipButton color
> Feat case node ignore

- src/components/DiffJsonView/VanillaJSONEditor.tsx
- src/components/panes/ReplayCaseDetailPage.tsx
- src/components/panes/ReplayDiffScenesPage/SubScenesMenu.tsx
- src/components/panes/index.ts
- src/components/replay/Case/Case.tsx
- src/components/replay/CaseDetail.tsx
- src/components/replay/ToCaseDetailButton.tsx
- src/i18n/locales/en-us/common.json
- src/i18n/locales/en-us/components.json
- src/i18n/locales/zh-cn/common.json
- src/i18n/locales/zh-cn/components.json
- src/services/Replay.service.ts
- src/services/Replay.type.ts
- src/store/index.ts
> Feat scenes count

- src/components/appSetting/Record/FormItem/AgentHost.tsx
- src/components/appSetting/Record/index.tsx
- src/i18n/locales/en-us/common.json
- src/i18n/locales/zh-cn/common.json
- src/services/AppSetting.service.ts
refactor Agent Host  Modal to Table
> Feat agent table

- packages/arex/src/panes/ReplayCase/ReplayCase.tsx
- packages/arex/src/panes/ReplayDiffScenes/FlowTree.tsx
- packages/arex/src/panes/ReplayDiffScenes/ReplayDiffScenes.tsx
DiffScene Pane
1. compare config
2. failedOnly filter
> Feat diff scene comfig compare

- packages/arex-core/package.json
- packages/arex-core/src/components/icons/RequestMethodIcon/ArexIcon.tsx
- packages/arex-core/src/components/icons/RequestMethodIcon/BorderIcon.tsx
- packages/arex-core/src/components/icons/RequestMethodIcon/CaseIcon.tsx
- packages/arex-core/src/components/icons/RequestMethodIcon/DeleteIcon.tsx
- packages/arex-core/src/components/icons/RequestMethodIcon/GetIcon.tsx
- packages/arex-core/src/components/icons/RequestMethodIcon/PatchIcon.tsx
- packages/arex-core/src/components/icons/RequestMethodIcon/PostIcon.tsx
- packages/arex-core/src/components/icons/RequestMethodIcon/PutIcon.tsx
- packages/arex-core/src/components/icons/RequestMethodIcon/index.ts
- packages/arex-core/src/layout/ArexMenuContainer.tsx
- packages/arex-core/src/layout/ArexPanesContainer.tsx
- packages/arex-core/src/menus/index.ts
- packages/arex-core/src/utils/ArexMenuManager.ts
- packages/arex-core/src/utils/index.ts
- packages/arex/package.json
- packages/arex/src/components/AppMenu.tsx
- packages/arex/src/components/MenuSelect.tsx
- packages/arex/src/menus/AppSetting.tsx
- packages/arex/src/menus/Collection/Collection.tsx
- packages/arex/src/menus/Collection/CollectionNodeTitle.tsx
- packages/arex/src/menus/Environment.tsx
- packages/arex/src/menus/Replay.tsx
- packages/arex/src/pages/index.tsx
- packages/arex/src/panes/Request/index.tsx
- packages/arex/src/store/useMenusPanes.ts
- pnpm-lock.yaml
1. colleciton tree draggable
2. arex pane draggable
3. arex/case Icon
4. arex menu searchBar fixed
> Feat draggable

- packages/arex/src/panes/AppSetting/Record/FormItem/IntegerStepSlider.tsx
allow the frequency of recording to 0
> Fix record frequency

- packages/arex-core/package.json
- packages/arex-core/src/components/DiffJsonView/index.tsx
- packages/arex/src/panes/AppSetting/CompareConfig/NodesIgnore/index.tsx
- packages/arex/src/panes/AppSetting/CompareConfig/index.tsx
- packages/arex/src/panes/ReplayCase/ReplayCase.tsx
- packages/arex/src/store/useUserProfile.ts
- pnpm-lock.yaml
1. feat: @arextest/vanilla-jsoneditor support multi-language
2. refactor: DiffJsonView rightClickHandler
3. chore: default language set to en
4. fix: getPath function basePath
5. fix: dependency contract update params
> fix: jsonDiffView optimize

- packages/arex/src/panes/Replay/AppTitle.tsx
https://github.com/arextest/arex/issues/383
> feat: refresh record count

- packages/arex-common/package.json
- packages/arex-core/package.json
- packages/arex-core/src/components/DiffJsonView/helper.ts
- packages/arex-core/src/components/DiffJsonView/index.tsx
- packages/arex-core/src/components/HighlightRowTable.tsx
- packages/arex-core/src/components/index.ts
- packages/arex-core/src/layout/ArexMenuContainer.tsx
- packages/arex/src/components/MenuSelect.tsx
- packages/arex/src/menus/Collection/Collection.tsx
- packages/arex/src/panes/AppSetting/CompareConfig/index.tsx
- packages/arex/src/panes/ReplayCase/ReplayCase.tsx
- packages/arex/src/panes/ReplayDiffScenes/ReplayDiffScenes.tsx
- pnpm-lock.yaml
1. DiffJson support diffMatch
2. adjust menu selected background color
3. refactor: PathHandler
4. fix: default configTypeValue
5. fix: replayCase decodeURIComponent operationName
> Feat: DiffJson support diffMatch

- packages/arex/src/panes/Replay/AppTitle.tsx
- packages/arex/src/panes/Replay/PlanReport.tsx
- packages/arex/src/panes/Replay/Replay.tsx
Allow view reports without recordings count
> fix: no record deps

- packages/arex-common/package.json
- packages/arex-common/src/components/DiffPath/DiffPathViewer.tsx
- packages/arex-core/package.json
- packages/arex-core/src/components/DiffJsonView/helper.ts
- packages/arex-core/src/components/DiffJsonView/index.tsx
- packages/arex-core/src/i18n/locales/cn/common.json
- packages/arex-core/src/i18n/locales/en/common.json
- packages/arex-core/src/utils/base64.ts
- packages/arex-core/src/utils/index.ts
- packages/arex-core/src/utils/json.ts
- packages/arex-core/src/utils/zstd.ts
- pnpm-lock.yaml
Support decode json node value by base64/zstd in JsonDiffViewer
> Feat decode json node value

- package.json
- packages/arex-common/package.json
- packages/arex-common/src/components/DiffPath/index.tsx
- packages/arex-core/package.json
- packages/arex-core/src/components/HighlightRowTable.tsx
- packages/arex-request/package.json
- packages/arex/package.json
- packages/arex/src/components/KeyboardShortcut.tsx
- packages/arex/src/components/PlanItemNavigation.tsx
- packages/arex/src/hooks/useInit.tsx
- packages/arex/src/i18n/locales/cn/common.json
- packages/arex/src/i18n/locales/cn/components.json
- packages/arex/src/i18n/locales/en/common.json
- packages/arex/src/i18n/locales/en/components.json
- packages/arex/src/pages/Login/index.tsx
- packages/arex/src/panes/Replay/AppTitle.tsx
- packages/arex/src/panes/Replay/PlanItem.tsx
- packages/arex/src/panes/Replay/PlanReport.tsx
- packages/arex/src/panes/Replay/Replay.tsx
- packages/arex/src/panes/ReplayCase/Case.tsx
- packages/arex/src/panes/ReplayCaseDetail/ReplayCaseDetail.tsx
- packages/arex/src/services/ReportService/queryPlanStatistics.ts
- packages/arex/vite.config.ts
- pnpm-lock.yaml
Feature：
1. 回放报告页 url query 使用 planId & planItemId 替换 row & current 保证唯一不变
2. 回放 case 页、case 详情页 url query 调整
3. 回放报告支持分享，通过分享链接打开的报告页只显示单条目标报告
4. 回放 case 页、差异场景页、case 详情页新增面包屑导航，跳转所属的报告页，以及快速跳转下一个错误 case
> refactor: replay plan key

- packages/arex/src/components/InterfaceSelect.tsx
- packages/arex/src/components/index.ts
- packages/arex/src/panes/AppSetting/CompareConfig/index.tsx
- packages/arex/src/panes/AppSetting/Record/index.tsx
- packages/arex/src/panes/Replay/AppTitle.tsx
- packages/arex/src/services/ApplicationService/getInterfacesList.ts
feat:
新增组件 `InterfaceSelect 接口选择器`：支持按接口类型聚合多选
> feat: interfaceSelect

- packages/arex/src/components/InterfaceSelect.tsx
- packages/arex/src/panes/AppSetting/Record/index.tsx
excludeServiceOperationSet / includeServiceOperations using operationName
> fix: record setting exclude/include using operationName

- packages/arex/src/components/CollectionSelect/CollectionSearchedList.tsx
- packages/arex/src/components/CollectionSelect/index.tsx
- packages/arex/src/panes/Replay/Replay.tsx
- packages/arex/src/panes/SystemSetting/Advanced/index.tsx
- packages/arex/src/services/SystemService/getSystemConfig.ts
- packages/arex/src/services/SystemService/index.ts
- packages/arex/src/services/SystemService/querySystemConfig.ts
- packages/arex/src/store/index.ts
- packages/arex/src/store/useSystemConfig.ts
- packages/arex/src/utils/globalStoreInit.ts
- pnpm-lock.yaml
feat: 
1. Collection 自动滚动定位
1. 搜索后滚动定位至目标节点
2. 拖动至上下边界时自动滚动
2. App 权限管理读取系统配置
> Feat permission controll

- package.json
- packages/arex-core/package.json
- packages/arex-core/src/components/DiffJsonView/index.tsx
- packages/arex-core/src/components/JSONEditor/PasswordAction.ts
- packages/arex-core/src/components/JSONEditor/index.tsx
- packages/arex-core/src/components/index.ts
- packages/arex-core/src/style.css
- packages/arex/package.json
- packages/arex/src/i18n/locales/cn/components.json
- packages/arex/src/i18n/locales/en/components.json
- packages/arex/src/panes/ReplayCase/CaseDiff/CaseDiffViewer.tsx
- packages/arex/vite.config.ts
- pnpm-lock.yaml
vanilla-jsoneditor 组件重构完成，已提交pr等待合并 https://github.com/josdejong/svelte-jsoneditor/pull/411
Feat:
1. 使用 svelte/action 定义 PasswordAction 自定义 Value 渲染组件
2. OnRenderContextMenu 支持返回 `false` 以取消 contextMenu 渲染
> feat: jsonEditor password action component

- package.json
- packages/arex-request/src/ArexRequest.tsx
- packages/arex-request/src/components/Request/RequestBody.tsx
- packages/arex/package.json
- packages/arex/src/components/CollectionSelect/CollectionNodeTitle.tsx
- packages/arex/src/components/CollectionSelect/index.tsx
- packages/arex/src/menus/Collection/Collection.tsx
- packages/arex/src/panes/Replay/AppTopBar/index.tsx
- packages/arex/src/panes/Replay/Replay.tsx
- packages/arex/src/panes/Request/Request.tsx
- packages/arex/src/store/useCollections.ts
- pnpm-lock.yaml
* fix: wrapper ref function into arrow function (#651)
* fix: collection load slow
* fix: deepClone tree data
* fix: deepClone tree data
* chore: update arex version
---------
> Fix hot fix v0.6.4 (#652)

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
> docs: add issue template

- packages/arex-core/package.json
- packages/arex-core/src/components/DiffJsonView/index.tsx
- packages/arex-core/src/components/DiffMatch/index.tsx
- packages/arex-core/src/components/JSONEditor/index.tsx
- packages/arex-core/src/i18n/locales/cn/common.json
- packages/arex-core/src/i18n/locales/en/common.json
- packages/arex/src/components/CollectionSelect/index.tsx
- packages/arex/src/panes/ReplayCase/CaseDiff/CaseDiffViewer.tsx
- packages/arex/src/services/ScheduleService/queryLogEntity.ts
- pnpm-lock.yaml
1. display data type on diff node
2. fade additional refer node
> Feat diff node optimize

- package.json
- packages/arex/package.json
> chore: update version to 0.7.3
